FROM golang:1.21-alpine

RUN apk add --no-cache git gcc musl-dev

RUN go install github.com/cosmtrek/air@v1.49.0

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]